# Generated by Django 2.2.8 on 2019-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'verbose_name': 'Сцена', 'verbose_name_plural': 'Сцены'},
        ),
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
    ]
