# Generated by Django 2.2.8 on 2019-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0002_auto_20191221_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название сцены'),
        ),
    ]
