# Generated by Django 2.2.8 on 2019-12-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0003_auto_20191222_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voice',
            options={'verbose_name': 'Решение цензора', 'verbose_name_plural': 'Решения цензоров'},
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(null=True, verbose_name='Комментарий/Пожелания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='desired_scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Scene', verbose_name='Желаемая сцена'),
        ),
        migrations.AlterField(
            model_name='request',
            name='format',
            field=models.CharField(choices=[('S', 'Сольное выступление'), ('G', 'Группа')], max_length=1, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя исполнителя/Название группы'),
        ),
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.TextField(verbose_name='Содержание заявки'),
        ),
        migrations.AlterField(
            model_name='sceneslot',
            name='count',
            field=models.PositiveSmallIntegerField(verbose_name='Количество выступлений в слоте'),
        ),
        migrations.AlterField(
            model_name='sceneslot',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Scene', verbose_name='Сцена'),
        ),
        migrations.AlterField(
            model_name='sceneslot',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.TimeSlot', verbose_name='Временной слот'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.PositiveSmallIntegerField(verbose_name='День выступления'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.CharField(choices=[('D', 'День'), ('E', 'Вечер'), ('LE', 'Поздний вечер')], max_length=2, verbose_name='Время выступления'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='censor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Цензор'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festival.Request', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice',
            field=models.CharField(choices=[('YES', 'За'), ('NO', 'Против'), ('ABS', 'Воздержался')], max_length=2, verbose_name='Решение цензора'),
        ),
    ]
