# Generated by Django 2.2.8 on 2019-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0004_auto_20191222_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первый день'), (2, 'Второй день')], verbose_name='День выступления'),
        ),
    ]
