# Generated by Django 2.2.8 on 2019-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0005_auto_20191222_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий/Пожелания'),
        ),
    ]
