# Generated by Django 2.2.8 on 2019-12-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191221_1924'),
        ('festival', '0006_auto_20191222_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Автор заявки'),
            preserve_default=False,
        ),
    ]
