# Generated by Django 2.2.8 on 2019-12-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0007_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='voice',
            field=models.CharField(choices=[('YES', 'За'), ('NO', 'Против'), ('ABS', 'Воздержался')], max_length=3, verbose_name='Решение цензора'),
        ),
    ]
