# Generated by Django 2.2.6 on 2019-12-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0008_auto_20191227_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='desired_scene',
            new_name='scene',
        ),
    ]
